# Generated by Django 3.2.8 on 2021-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
