# Generated by Django 3.2.8 on 2021-12-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_comment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watching',
        ),
    ]
