# Generated by Django 3.2.8 on 2021-12-04 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20211204_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
