# Generated by Django 3.2.8 on 2021-12-04 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20211204_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
