# Generated by Django 3.2.8 on 2021-12-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_alter_watchlist_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watching',
            field=models.BooleanField(default=False),
        ),
    ]
