# Generated by Django 3.2.8 on 2021-12-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_watchlist_watching'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='user',
            new_name='prof',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='title',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.ManyToManyField(related_name='name', to='auctions.Listing'),
        ),
    ]
