# Generated by Django 3.2.8 on 2021-12-04 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20211204_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='prof',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(related_name='name', to='auctions.Listing'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='name',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
