# Generated by Django 3.2.8 on 2021-12-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_listing_current_bid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
